from animals.alligator import Alligator
from animals.anaconda import Anaconda
from animals.animal import Animal
from animals.catfish import Catfish
from animals.copperhead import Copperhead
from animals.donkey import Donkey
from animals.frog import Frog
from animals.goat import Goat
from animals.goldfish import Goldfish
from animals.king_cobra import King_Cobra
from animals.lama import Lama
from animals.lion import Lion
from animals.mallard import Mallard
from animals.monkey import Monkey
from animals.python import Python
from animals.rat_snake import Rat_Snake